server:
  port: 8080
spring:
  datasource:
    platform: h2      # will run data-h2.sql file
    url: jdbc:h2:mem:springDb
    username: sa
    password:
    driver-class-name: org.h2.Driver

# Enabling H2 Console
  h2:
    console:
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create    # if this enabled no need for schema.sql
#      ddl-auto: validate
#      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


