spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employeeDB
    username: root
    password: Talent_123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: validate
      ddl-auto: create
#      ddl-auto: update
  data:
    mongodb:
      port: 27017
      host: localhost
      database: sampleDb


