server:
  port: 8080
spring:
  datasource:
    platform: mysql    # will run data-mysql.sql file
    url: jdbc:mysql://127.0.0.1:3306/springDb
    username: root
    password: Talent_123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate    # if this enabled no need for schema.sql
#      ddl-auto: validate
#      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp



